import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

const JetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={JetBrainsMono.className}>{children}</body>
    </html>
  );
}
