import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

const JetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={JetBrainsMono.className}>
        <div className='mx-auto min-h-screen max-w-2xl border border-red-500'>
          {children}
        </div>
      </body>
    </html>
  );
}
