import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { JetBrains_Mono } from "next/font/google";
import "../theme-config.css";
const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-JetBrainsMono",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={JetBrainsMono.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
